chore: include datadog/istio labels and annotations by default when t…
blablacar/tlsmonitor pull request #31
Opened 2024-05-02 15:10 UTC by benoitpuertolas

…he associated flag is on

2024-05-06 06:37 UTC, frgaudet requested changes

2024-05-06 06:37 UTC, frgaudet commented on _infra/templates/deployment.yaml
> +              "namespace": "tlsmonitor",
don't prefix the metrics with the namespace: it's harder to find them in datadog metric explorer

2024-05-06 06:37 UTC, frgaudet commented on _infra/values.yaml
> +  team: team_core_infrastructure
team: infra ?

2024-05-06 15:15 UTC, frivoire commented on _infra/templates/deployment.yaml
> +              "namespace": "tlsmonitor",
If you don't define a namespace here, you need to be sure that the (open)metrics themselves are somehow prefixed.
Otherwise, the global BBC's metrics ecosystem is just a mess 😬

So, this config looks nice to me 👍 
And BTW it's the one already in place today AFAIK

2024-05-06 15:16 UTC, frivoire reviewed
I haven't reviewed the details, but the global principle looks nice 👍

2024-05-07 09:16 UTC, benoitpuertolas commented on _infra/values.yaml
You're right, it is better like this! I also make the tag default to the chart version.

2024-05-07 13:15 UTC, frgaudet commented on _infra/templates/deployment.yaml
> +              "namespace": "tlsmonitor",
Well no.
If you prefix your metric by namespace, you can't have stats over 2 different namespace because `a.host_cert_expiration_seconds` will be a different metric from `b.host_cert_expiration_seconds`

It's better to have the same name (unique name in the cluster of course which is the case here) but namespace as a dimension
`host_cert_expiration_seconds{namespace=a or namespace=b}`

2024-05-07 13:16 UTC, frgaudet commented on _infra/templates/deployment.yaml
> +              "namespace": "tlsmonitor",
It's maybe like that in the first place but it's not the good practice

2024-05-07 13:23 UTC, frgaudet commented on _infra/templates/deployment.yaml
> +              "namespace": "tlsmonitor",
So it means that the prefix is an important config part of the metric name which must be homogeneous in all clusters in order to have a unified metric... This is not really the way to go in my opinion

2024-05-07 13:25 UTC, benoitpuertolas commented on _infra/templates/deployment.yaml
> +              "namespace": "tlsmonitor",
I totally agree to not append the kubernetes namespace as prefix but here we just put "tlsmonitor" as a prefix for all metrics generated by tlsmonitor (for all namespaces).
And actually, moving this from the kube_manifest repo to the helm chart make it homogeneous by default.

2024-05-07 13:32 UTC, frgaudet approved these changes

2024-05-07 13:34 UTC, frgaudet commented on _infra/templates/deployment.yaml
> +              "namespace": "tlsmonitor",
ok fine let's continue like it is , it shouldn't have been done this way at the beginning  😖

2024-05-10 12:37 UTC, frivoire commented on _infra/templates/deployment.yaml
> +              "namespace": "tlsmonitor",
Fred:
> If you prefix your metric by namespace, you can't have stats over 2 different namespace because a.host_cert_expiration_seconds will be a different metric from b.host_cert_expiration_seconds
> It's better to have the same name (unique name in the cluster of course which is the case here) but namespace as a dimension
host_cert_expiration_seconds{namespace=a or namespace=b}

Benoit:
> I totally agree to not append the kubernetes namespace as prefix

In the end, we all agree:
The concept of namespace here is not _K8S_ namespace, but another concept of "_metrics_" namespace (a prefix in their name, to group them).
In practice, this "namespace" should not be configured differently per deployment of tlsmonitor, but always stay the same value (which is configured here, in the chart).

And it's still useful to have this namespace/prefix thing, so that metrics are not mixed up in datadog (cf Benoit's remark above about "ambiguous"). So if it was remade from scratch today, I still think it should be done the same way.

2024-05-10 12:39 UTC, frivoire approved these changes
OK for me 👍

And if you want, you can include this small improvement too:

2024-06-03 07:59 UTC, merged